name: Check Lint and Sentantic Title Pull Request
on:
    pull_request:
        types: [opened, synchronize, reopened]
        branches:
            - main

jobs:
    lint:
        name: Lint Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v4
              with:
                  node-version: 18
                  cache: "npm"
            - run: npm install
            - run: npm lint
    pr-title:
        name: Semantic PR Title
        runs-on: ubuntu-latest
        steps:
        - uses: amannn/action-semantic-pull-request@v5
            env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

